# Generated by Django 5.2 on 2025-04-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('className', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('math', models.DecimalField(decimal_places=2, max_digits=5)),
                ('physics', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chemistry', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
